import { jsPDF } from "jspdf";
import "jspdf-autotable";

export async function generatePDFReport(
  type: "customers" | "loans" | "payments" | "outstanding" | "overdue",
  data: any[],
  settings: any
) {
  const doc = new jsPDF() as any;

  // Header Title
  const companyName = settings.companyName || "Vyas Finance";
  const address = settings.companyAddress || "MG Road, Bengaluru, KA 560001";
  const phone = settings.contactNumber || "+91 98450 00000";

  // Date and User
  const reportDate = new Date().toLocaleDateString("en-IN", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  
  const userStr = typeof localStorage !== "undefined" ? localStorage.getItem("user") : null;
  const currentUser = userStr ? JSON.parse(userStr) : { username: "admin", role: "Admin" };
  const generatedBy = `${currentUser.username} (${currentUser.role})`;

  // Branding Title
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(179, 158, 106); // Gold color #b39e6a
  doc.text(companyName, 15, 20);

  doc.setFont("Helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(`${address} | Contact: ${phone}`, 15, 26);

  // Line Separator
  doc.setDrawColor(200, 200, 200);
  doc.line(15, 30, 195, 30);

  // Report details
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(40, 40, 40);
  const titleMap = {
    customers: "Branch Customers Listing Report",
    loans: "Gold Loans Disbursement Report",
    payments: "Payments & Collections History Report",
    outstanding: "Outstanding Loan Balance Report",
    overdue: "Overdue Accounts Listing Report",
  };
  doc.text(titleMap[type], 15, 40);

  doc.setFont("Helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text(`Report Date: ${reportDate}`, 15, 46);
  doc.text(`Generated By: ${generatedBy}`, 130, 46);

  // Setup table columns and body
  let columns: string[] = [];
  let rows: any[][] = [];

  if (type === "customers") {
    columns = ["Cust ID", "Customer Name", "Phone", "Aadhaar", "Occupation", "Joined Date"];
    rows = data.map((c) => [
      c.customerNumber,
      c.name,
      c.phone,
      c.aadhaar,
      c.occupation,
      new Date(c.createdAt).toLocaleDateString("en-IN"),
    ]);
  } else if (type === "loans") {
    columns = ["Loan No.", "Customer Name", "Loan Date", "Maturity", "Disbursed", "Rate", "Status", "Balance"];
    rows = data.map((l) => [
      l.loanNumber,
      l.customer?.name || "-",
      l.loanDate,
      l.maturityDate,
      `INR ${l.loanAmount.toLocaleString("en-IN")}`,
      `${l.interestRate}%`,
      l.status,
      `INR ${l.balance.toLocaleString("en-IN")}`,
    ]);
  } else if (type === "payments") {
    columns = ["Receipt No.", "Loan No.", "Customer", "Date", "Paid Mode", "Amount"];
    rows = data.map((p) => [
      p.receiptNumber,
      p.loan?.loanNumber || "-",
      p.loan?.customer?.name || "-",
      p.paymentDate,
      p.paymentMode,
      `INR ${p.amount.toLocaleString("en-IN")}`,
    ]);
  } else if (type === "outstanding") {
    columns = ["Loan No.", "Customer Name", "Disbursed", "Interest Rate", "Due Date", "O/S Balance"];
    rows = data.map((l) => [
      l.loanNumber,
      l.customer?.name || "-",
      `INR ${l.loanAmount.toLocaleString("en-IN")}`,
      `${l.interestRate}%`,
      l.maturityDate,
      `INR ${l.balance.toLocaleString("en-IN")}`,
    ]);
  } else if (type === "overdue") {
    columns = ["Loan No.", "Customer Name", "Phone", "Maturity Date", "O/S Balance"];
    rows = data.map((l) => [
      l.loanNumber,
      l.customer?.name || "-",
      l.customer?.phone || "-",
      l.maturityDate,
      `INR ${l.balance.toLocaleString("en-IN")}`,
    ]);
  }

  // Draw AutoTable
  doc.autoTable({
    startY: 52,
    head: [columns],
    body: rows,
    theme: "striped",
    headStyles: {
      fillColor: [179, 158, 106], // Vyas gold
      textColor: [255, 255, 255],
      fontSize: 9,
      fontStyle: "bold",
    },
    bodyStyles: {
      fontSize: 8,
    },
    alternateRowStyles: {
      fillColor: [250, 248, 242],
    },
    margin: { left: 15, right: 15 },
    didDrawPage: (data: any) => {
      // Footer page numbering
      const str = "Page " + doc.internal.getNumberOfPages();
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(
        str,
        data.settings.margin.left,
        doc.internal.pageSize.height - 10
      );
      doc.text(
        "Vyas Finance Gold Loan Management",
        doc.internal.pageSize.width - 70,
        doc.internal.pageSize.height - 10
      );
    },
  });

  doc.save(`${type}_report_${new Date().toISOString().split("T")[0]}.pdf`);
}

export async function downloadReceiptPDF(payment: any, settings: any) {
  const doc = new jsPDF() as any;

  // Header Title
  const companyName = settings?.companyName || "Vyas Finance";
  const address = settings?.companyAddress || "MG Road, Bengaluru, KA 560001";
  const phone = settings?.contactNumber || "+91 98450 00000";

  // Receipt details
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(179, 158, 106); // Gold color #b39e6a
  doc.text(companyName, 15, 20);

  doc.setFont("Helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(`${address} | Contact: ${phone}`, 15, 26);

  // Line Separator
  doc.setDrawColor(200, 200, 200);
  doc.line(15, 30, 195, 30);

  // Document Title
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(40, 40, 40);
  doc.text("PAYMENT RECEIPT", 15, 42);

  // Receipt Box (Gray background container)
  doc.setFillColor(248, 246, 240);
  doc.rect(15, 48, 180, 80, "F");

  doc.setFont("Helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);

  // Content columns inside box
  doc.text(`Receipt Number:`, 20, 58);
  doc.setFont("Helvetica", "bold");
  doc.text(payment.receiptNumber || "-", 60, 58);

  doc.setFont("Helvetica", "normal");
  doc.text(`Customer Name:`, 20, 68);
  doc.text(payment.loan?.customer?.name || payment.customerName || "-", 60, 68);

  doc.text(`Loan Number:`, 20, 78);
  doc.text(payment.loan?.loanNumber || "-", 60, 78);

  doc.text(`Payment Date:`, 20, 88);
  doc.text(payment.paymentDate || "-", 60, 88);

  doc.text(`Payment Mode:`, 20, 98);
  doc.text(payment.paymentMode || "-", 60, 98);

  doc.text(`Amount Paid:`, 20, 108);
  doc.setFont("Helvetica", "bold");
  doc.setTextColor(34, 139, 34); // Forest Green
  doc.text(`INR ${(payment.amount || 0).toLocaleString("en-IN")}`, 60, 108);

  doc.setFont("Helvetica", "normal");
  doc.setTextColor(60, 60, 60);
  doc.text(`Remaining Balance:`, 20, 118);
  doc.setFont("Helvetica", "bold");
  doc.setTextColor(179, 158, 106);
  const bal = payment.loan?.outstandingBalance !== undefined ? payment.loan.outstandingBalance : (payment.remainingBalance || 0);
  doc.text(`INR ${bal.toLocaleString("en-IN")}`, 60, 118);

  // QR Code (Future Ready placeholder)
  doc.setDrawColor(180, 180, 180);
  doc.rect(145, 58, 40, 40);
  doc.setFont("Helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text("[ QR Code ]", 153, 76);
  doc.text("Future Ready", 151, 80);

  // Footer / Terms
  doc.setFont("Helvetica", "italic");
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text("Thank you for your payment. This is a computer-generated receipt and does not require a signature.", 15, 140);
  
  doc.save(`receipt_${payment.receiptNumber}.pdf`);
}

export async function downloadLoanAgreementPDF(loan: any, customer: any, settings: any) {
  const doc = new jsPDF() as any;

  const companyName = settings?.companyName || "Vyas Finance";
  const address = settings?.companyAddress || "MG Road, Bengaluru, KA 560001";
  const phone = settings?.contactNumber || "+91 98450 00000";

  doc.setFont("Helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(179, 158, 106);
  doc.text(companyName, 15, 20);

  doc.setFont("Helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(`${address} | Contact: ${phone}`, 15, 26);

  doc.setDrawColor(200, 200, 200);
  doc.line(15, 30, 195, 30);

  doc.setFont("Helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(40, 40, 40);
  doc.text("GOLD LOAN AGREEMENT", 15, 42);

  doc.setFont("Helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);

  doc.text("This agreement is executed between the Lender and the Customer details below:", 15, 50);

  // Lender Details
  doc.setFont("Helvetica", "bold");
  doc.text("LENDER DETAILS", 15, 60);
  doc.setFont("Helvetica", "normal");
  doc.text(`Name: ${companyName}`, 15, 66);
  doc.text(`Address: ${address}`, 15, 72);

  // Customer Details
  doc.setFont("Helvetica", "bold");
  doc.text("CUSTOMER DETAILS", 110, 60);
  doc.setFont("Helvetica", "normal");
  doc.text(`Name: ${customer.name}`, 110, 66);
  doc.text(`Cust ID: ${customer.customerNumber}`, 110, 72);
  doc.text(`Phone: ${customer.phone}`, 110, 78);

  doc.line(15, 84, 195, 84);

  // Loan Details
  doc.setFont("Helvetica", "bold");
  doc.text("LOAN DETAILS", 15, 94);
  doc.setFont("Helvetica", "normal");
  doc.text(`Loan Number: ${loan.loanNumber}`, 15, 100);
  doc.text(`Loan Date: ${loan.loanDate}`, 15, 106);
  doc.text(`Maturity Date: ${loan.loanClosingDate}`, 15, 112);
  
  doc.text(`Loan Amount: INR ${loan.loanAmount.toLocaleString("en-IN")}`, 110, 100);
  doc.text(`Interest Rate: ${loan.interestRate}% p.a.`, 110, 106);
  doc.text(`Loan Status: ${loan.status}`, 110, 112);

  doc.line(15, 118, 195, 118);

  // Ornaments Table Header
  doc.setFont("Helvetica", "bold");
  doc.text("COLLATERAL (GOLD ORNAMENTS)", 15, 128);

  let columns = ["Ornament Type", "Purity", "Gross Wt (g)", "Net Wt (g)", "Est Value"];
  let rows = (loan.ornaments || []).map((o: any) => [
    o.type,
    o.category === "Other" ? (o.customOrnamentName || "Other") : o.category,
    `${o.grossWeight}g`,
    `${o.netWeight}g`,
    `INR ${o.estimatedValue.toLocaleString("en-IN")}`
  ]);

  doc.autoTable({
    startY: 134,
    head: [columns],
    body: rows,
    theme: "striped",
    headStyles: {
      fillColor: [179, 158, 106],
      textColor: [255, 255, 255]
    },
    margin: { left: 15, right: 15 }
  });

  const finalY = doc.lastAutoTable.finalY + 15;
  doc.setFont("Helvetica", "italic");
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text("I hereby declare that the gold ornaments pledged are my own property and details specified are correct.", 15, finalY);

  doc.save(`agreement_${loan.loanNumber}.pdf`);
}
